import React from 'react';
import Head from 'next/head';
import Textline from 'ui-components/textline';
import styles from '../styles/Home.module.css';

export default class Home extends React.Component {
    render() {
        return (
            <div className={styles.container}>
                <Head>
                    <title>Next UI - Workspace</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Textline 
                    placeholder="Enter Text"
                />
            </div>
        );
    }
}
